project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "About me"
        contents:
          - href: index.qmd
            text: Home
          - href: listing.qmd
            text: Index of posts
          - href: Publications.qmd
            text: Publications

      - section: "Posts"
        contents:
          - section: "Evidence synthesis"
            contents:
              - href: Ecology_SR.qmd
                text: Rapid review short-cuts
              - href: What_makes_a_good_systematic_review.qmd
                text: What makes a good evidence synthesis?
              - href: Ecology_is_not_medicine.qmd
                text: Ecology is not medicine
              - href: Dynamic_Meta_analysis.qmd
                text: Dynamic Meta-analysis - When Transparency Meets Multiplicity

          - section: "Data & tools"
            contents:
              - href: making_missing_data_work.qmd
                text: Missing data
              - href: OpenAlex.qmd
                text: Using OpenAlex to get publication metadata

          - section: "Community"
            contents:
              - href: ESHackathon.qmd
                text: What is the ESHackathon?

      - section: "Presentations"
        contents:
          - href: presentations/page-reveal.html
            text: Leveraging open tools for evidence synthesis

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual
